### ISSUE TITLE
Alternative to the Extension

### ISSUE THREAD

**Issue by Akemi** [yene/Safari-Backspace#1]
not really an issue, but an alternative. this will work too:
```
defaults write com.apple.Safari NSUserKeyEquivalents -dict-add Back "\U232b"
```
this basically adds a new shortcut for Safari in the System Preferences. the System Preferences won't accept the Backspace key as shortcut, but it is possible to add that shortcut via that command line command.
![Screenshot 2019-04-07 at 14 16 57](https://user-images.githubusercontent.com/680386/55683435-14028800-5940-11e9-95f7-290c99cb57a6.png)

not to be confused with the old and not working defaults.
```
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool YES
```

**Comment by yene** [comment]
Thanks for the tipp, I tried it but could not get it to work on my mac. I have Safari 12.0.3

```
$ defaults read com.apple.Safari NSUserKeyEquivalents -dict-add Back "\U232b"
{
    Back = "\\U232b";
}
```

any idea why it did not work?

**Comment by Akemi** [comment]
i am on safari 12.1 and macOS 10.14.4. maybe that makes a difference. i have the same/similar output:
```
$ defaults read com.apple.Safari NSUserKeyEquivalents
{
    Back = "\\U232b";
    "Show Next Tab" = "~.";
    "Show Previous Tab" = "~,";
}
```
does it show the shortcut in the system preferences like on my screenshot?

**Comment by pflind** [comment]
@Akemi I'm on 12.1 / 10.14.4 and neither does it work for me. The shortcut is not added to the system preferences.

**Comment by Akemi** [comment]
that's weird. i wonder what the difference is. here another screenshot of the Safari menu properly showing the shortcut.
![Screenshot 2019-04-11 at 19 35 46](https://user-images.githubusercontent.com/680386/55978812-07a86300-5c91-11e9-844a-5a8a21674367.png)

**Comment by Akemi** [comment]
do you have a different OS language and "Back" isn't called back?

**Comment by pflind** [comment]
I have a swedish keyboard but use English as language in macOS. Here's a screenshot, I have **Command[** `⌘[` instead of the arrow symbol in your screenshot:

<img width="504" alt="Screenshot 2019-04-11 at 23 56 29" src="https://user-images.githubusercontent.com/7270464/55992662-c1b1c600-5cb5-11e9-996b-bc8c61cf9819.png">

Do you know what the unicode is for `⌘[`?

**Comment by Akemi** [comment]
binds with `@[ `and should be `\U0040\U005B`.

**Comment by pflind** [comment]
Thank you, but it still doesn't work for me. It's great tip, too bad that I don't have any luck with it.

**Comment by yene** [comment]
@Akemi did you disable System Integrity Protection? You can check with `csrutil status`

**Comment by Akemi** [comment]
yes, i actually did disable it.
