### ISSUE TITLE
Compile for High Sierra

### ISSUE THREAD

**Issue by tscheffl** [yene/Safari-Backspace#2]
Could you also provide a version that is compatible with High Sierra? Safari 12.1 now does no longer honor the old defaults.

**Comment by yene** [comment]
hi, I think on older macOS you can enable it with this Terminal command:
`defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool YES`

**Comment by tscheffl** [comment]
This did work with previous versions of Safari. But since the last update to Safari 12.1 it no longer works on High Sierra for me.

Thomas


> Am 09.04.2019 um 17:53 schrieb Yannick Weiss <notifications@github.com>:
> 
> defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool YES

**Comment by yene** [comment]
I hope this works https://github.com/yene/Safari-Backspace/releases/tag/v1.0.1

**Comment by tscheffl** [comment]
Thank you!
Works very well on High Sierra and Safari 12.1

Thomas
