### ISSUE TITLE
Shift + Backspace to go Forward?

### ISSUE THREAD

**Issue by pkamb** [yene/Safari-Backspace#3]
In Chrome the <kbd>Shift</kbd><kbd>Backspace</kbd> moves Forward, as an inverse of backspace-to-go-back.

Would that be possible in this extension?

Thanks! Backspace works great.

**Comment by yene** [comment]
Added https://github.com/yene/Safari-Backspace/releases/download/v1.1/Safari.Backspace.app.zip
