### ISSUE TITLE
Build for Apple Silicon

### ISSUE THREAD

**Issue by jgale** [yene/Safari-Backspace#4]
I still love this extension and it was one of the first things I installed on my new M1 MacBook. It's one of the only things that requires Rosetta on my computer. Is it possible to make a universal binary to avoid requiring Rosetta?

(Not that I'm worried about performance, I'm just trying to live an x86-free existence).

Thanks!

**Comment by yene** [comment]
added https://github.com/yene/Safari-Backspace/releases/tag/v1.2

**Comment by jgale** [comment]
Thank you so much! It works like a charm.
